apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  
patches:
  - path: patch-console-notification.yaml
    target:
      kind: ConsoleNotification
      name: environment-banner
