kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: langchain-wb
  namespace: rag-llm-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeMode: Filesystem